import CreateSessionClient from './create-session-client';

// When the marketing build is exported statically for GitHub Pages we still
// need at least one entry for every dynamic route. The actual project IDs
// are generated by the API at runtime, so the static demo simply renders
// a placeholder shell.
export function generateStaticParams() {
  return [{ id: 'demo' }];
}

export const dynamicParams = true;

export default function Page() {
  return <CreateSessionClient />;
}
